apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
    - port: 1883
      targetPort: 1883
  type: LoadBalancer
  loadBalancerIP: "35.233.127.48"
